### ISSUE TITLE
Error in function "covsurf"

### ISSUE THREAD

**Issue by valerieodeh** [robingenuer/CoVVSURF#1]
Hi!
I am trying to reproduce your example and getting the following error when trying to use the function covsurf: 

Error in library(robingenuer/CoVVSURF) : 'package' must be of length 1
Execution halted

Please advise

Thanks in advance

**Comment by robingenuer** [comment]
Hi,
I think that is the way you load the package that produces the error.
If you correctly installed the package using those commands: 

`if (!requireNamespace("devtools", quietly = TRUE)) {
    install.packages("devtools")}
devtools::install_github("robingenuer/VSURF")`

You may load the package using:

`library(CoVVSURF)`

I hope it helps,
Robin

**Comment by valerieodeh** [comment]
Thank you for your help! It worked!
Valerie
